version: "2" # 원래 3.8이었으나 리눅스 환경에서 build 하기 위해 2.0으로 변경
services:
  devnetwork.admin-app:
    container_name: devnetwork.admin-app
    image: mrcocoball/dateplanner_admin:dev
    environment: # .env 파일에 저장했던 환경 변수
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - KAKAO_REST_API_KEY=${KAKAO_REST_API_KEY}
      - SECRET_USERNAME=${SECRET_USERNAME}
      - SECRET_PASSWORD=${SECRET_PASSWORD}
      - VIRTUAL_HOST = devnetwork.admin-app
    ports:
      - "82:8085" # 기본 포트
    networks:
      - devnetwork
    volumes:
      - /home/mrcocoball/date_planner/image:/home/mrcocoball/date_planner/image
    restart: always # depends on은 실행 순서만 컨트롤, 컨테이너 안의 서비스가 실행 가능한 상태인지는 확인하지 않으므로
    # DB가 실행 가능한 상태가 아니여서 실패할 경우 재시작하도록 설정

# API 서버 - 어드민 서버 컨테이너 간 연결을 위한 network
networks:
  devnetwork:
    external: true