server:
  port: 8084

spring:
  profiles:
    active: local
    group:
      local:
        - common
      prod:
        - common
    include: jwt

springdoc:
  paths-to-match:
    - /api/**

logging:
  level:
    org.hibernate.SQL: debug
    #org.hibernate.type.descriptor.sql.BasicBinder: trace
---

spring:
  config:
    activate:
      on-profile: common

kakao:
  rest:
    api:
      key: ${KAKAO_REST_API_KEY}

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:4000/date_planner
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create
      use-new-id-generator-mappings: false # hibernate_sequence false
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        hibernate.default_batch_fetch_size: 100
    use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:4000/date_planner
    url: jdbc:mariadb://backend-database:3306/backend-database
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      generate-ddl: true
      ddl-auto: create
      use-new-id-generator-mappings: false # hibernate_sequence false
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        hibernate.default_batch_fetch_size: 100
    use_sql_comments: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
---
